//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeProjesi_Universite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VizeProjesi_UniversiteEntities7 : DbContext
    {
        public VizeProjesi_UniversiteEntities7()
            : base("name=VizeProjesi_UniversiteEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_APersonel> Tbl_APersonel { get; set; }
        public virtual DbSet<Tbl_IPersonel> Tbl_IPersonel { get; set; }
        public virtual DbSet<Tbl_Ogrenci> Tbl_Ogrenci { get; set; }
        public virtual DbSet<Tbl_Rapor> Tbl_Rapor { get; set; }
        public virtual DbSet<TblBolum> TblBolum { get; set; }
    }
}
