//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeProjesi_Universite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public int Adminid { get; set; }
        public string AdminKullaniciAdi { get; set; }
        public string AdminParola { get; set; }
        public string AdminRol { get; set; }
        public Nullable<int> AdminIPersonelid { get; set; }
    
        public virtual Tbl_IPersonel Tbl_IPersonel { get; set; }
    }
}
