//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeProjesi_Universite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogrenci()
        {
            this.Tbl_Rapor = new HashSet<Tbl_Rapor>();
        }
    
        public int Ogrenciid { get; set; }
        public string OgrenciAdSoyad { get; set; }
        public Nullable<long> OgrenciNumara { get; set; }
        public Nullable<int> OgrenciBolumid { get; set; }
        public Nullable<decimal> OgrenciNot { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblBolum TblBolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Rapor> Tbl_Rapor { get; set; }
    }
}
