//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeProjesi_Universite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_IPersonel()
        {
            this.Tbl_Admin = new HashSet<Tbl_Admin>();
            this.Tbl_Rapor = new HashSet<Tbl_Rapor>();
        }
    
        public int IPersonelid { get; set; }
        public string IPersonelAdSoyad { get; set; }
        public Nullable<System.DateTime> IPersonelBaslamaT { get; set; }
        public Nullable<System.DateTime> IPersonelAyrilmaT { get; set; }
        public string IPersonelBirimi { get; set; }
        public Nullable<int> IPersonelDahiliNumara { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Admin> Tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Rapor> Tbl_Rapor { get; set; }
    }
}
