//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeProjesi_Universite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rapor
    {
        public int Raporid { get; set; }
        public Nullable<int> RaporOgrenciid { get; set; }
        public Nullable<int> RaporAPersonelid { get; set; }
        public Nullable<int> RaporIPersonelid { get; set; }
    
        public virtual Tbl_APersonel Tbl_APersonel { get; set; }
        public virtual Tbl_IPersonel Tbl_IPersonel { get; set; }
        public virtual Tbl_Ogrenci Tbl_Ogrenci { get; set; }
    }
}
